name: codestats_flutter
description: View codestats in your phone

version: 1.0.22+23

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    version: <=1.2.1
  package_info: ^0.3.2
  date_format: ^1.0.5
  charts_flutter:
  superpower: ^0.4.0
  flutter_circular_chart:
  fl_chart: ^0.1.5
  intl: ^0.15.7
  json_annotation: ^2.0.0
  phoenix_wings: ^0.2.1
  dio: 2.1.13
  flutter_spinkit: ^3.1.0
  rxdart: ^0.20.0
  share: ^0.5.3
  auto_size_text: ^0.3.0
  random_color: ^1.0.3
  path_provider: ^1.0.0
  flutter_inappbrowser: ^1.2.1
  flip_panel: ^1.0.0
  draggable_scrollbar: ^0.0.4
  bubble_tab_indicator: ^0.1.4
  image: ^2.1.4
  # Music related
  tonic: 0.2.3
  flutter_midi: ^1.0.0
  # ???
  confetti: ^0.1.0

dev_dependencies:
  json_serializable: ^2.0.1
  build_runner: ^1.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/icon/ic_launcher.png
    - midi/zelda.sf2

  fonts:
    - family: OCRAEXT
      fonts:
        - asset: fonts/OCRAEXT.TTF
